#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */

const fs = require('fs')
const path = require('path')
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

const question = (prompt) => new Promise((resolve) => rl.question(prompt, resolve))

async function setupEnvironment() {
  console.log('\n🚀 Project Kairos Environment Setup\n')

  // Check if firebase-service-account.json exists
  const serviceAccountPath = path.join(__dirname, '..', 'firebase-service-account.json')
  let firebaseAdmin = {}

  if (fs.existsSync(serviceAccountPath)) {
    console.log('✅ Found firebase-service-account.json')
    firebaseAdmin = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'))
  } else {
    console.log('❌ firebase-service-account.json not found!')
    console.log('   Please download it from Firebase Console > Project Settings > Service Accounts')
    console.log('   and save it as firebase-service-account.json in the project root\n')
  }

  // Collect environment variables
  console.log('Please provide the following information:\n')

  const config = {
    // Database
    DATABASE_URL: await question('Supabase Database URL (postgresql://...): '),

    // Firebase Frontend Config
    VITE_FIREBASE_API_KEY: await question('Firebase API Key: '),
    VITE_FIREBASE_AUTH_DOMAIN: 'project-kairos-2885a.firebaseapp.com',
    VITE_FIREBASE_PROJECT_ID: 'project-kairos-2885a',
    VITE_FIREBASE_STORAGE_BUCKET: 'project-kairos-2885a.appspot.com',
    VITE_FIREBASE_MESSAGING_SENDER_ID: await question('Firebase Messaging Sender ID: '),
    VITE_FIREBASE_APP_ID: await question('Firebase App ID: '),

    // Firebase Admin (from service account if available)
    FIREBASE_PROJECT_ID: firebaseAdmin.project_id || 'project-kairos-2885a',
    FIREBASE_CLIENT_EMAIL: firebaseAdmin.client_email || (await question('Firebase Client Email: ')),
    FIREBASE_PRIVATE_KEY: firebaseAdmin.private_key || (await question('Firebase Private Key: ')),

    // API Configuration
    VITE_API_URL: 'http://localhost:3001',
    NODE_ENV: 'development',

    // Development Settings
    LOG_LEVEL: 'debug',
    ENABLE_QUERY_LOGGING: 'true',
  }

  // Generate .env.local content
  let envContent = '# .env.local\n# Generated by setup-env.js\n\n'

  for (const [key, value] of Object.entries(config)) {
    if (key === 'FIREBASE_PRIVATE_KEY' && value) {
      // Properly escape private key
      envContent += `${key}="${value.replace(/\n/g, '\\n')}"\n`
    } else {
      envContent += `${key}=${value}\n`
    }
  }

  // Write .env.local
  const envPath = path.join(__dirname, '..', '.env.local')
  fs.writeFileSync(envPath, envContent)

  console.log('\n✅ Created .env.local successfully!')

  // Add .env.local to .gitignore if not already there
  const gitignorePath = path.join(__dirname, '..', '.gitignore')
  const gitignoreContent = fs.readFileSync(gitignorePath, 'utf8')

  if (!gitignoreContent.includes('.env.local')) {
    fs.appendFileSync(gitignorePath, '\n# Local environment\n.env.local\nfirebase-service-account.json\n')
    console.log('✅ Added .env.local to .gitignore')
  }

  console.log('\nNext steps:')
  console.log('1. Run: yarn db:generate')
  console.log('2. Run: yarn db:push')
  console.log('3. Run: yarn dev')

  rl.close()
}

setupEnvironment().catch(console.error)
